version: '3.8'

services:
  php:
    # image: php:fpm
    environment:
      # XDEBUG_MODE: "debug,develop"
      XDEBUG_MODE: "off"
    restart: unless-stopped
    build:
      context: ./config/docker/php/
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html
      - ./config/docker/php/php.ini:/usr/local/etc/php/php.ini
      - '~/.composer/docker-cache/:/home/phpdev/.composer:cached'
      - '~/.config/composer/:/home/phpdev/.config/composer:cached'
      - vscode-extensions:/home/phpdev/.vscode-server/extensions
    links:
    - mysql
    networks:
      - study-cakephp3-net
    # platform: linux/amd64

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-80}:80"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html'
      - ./config/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      # so we can cache our github tokens
    networks:
      - study-cakephp3-net
    links:
      - php
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    restart: unless-stopped
    image: 'mysql/mysql-server:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - 'study-cakephp3-volume:/var/lib/mysql'
    networks:
    - study-cakephp3-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    # platform: linux/arm64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"  # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - study-cakephp3-net

networks:
  study-cakephp3-net:
    driver: bridge
volumes:
  study-cakephp3-volume:
    driver: local
  vscode-extensions:
    driver: local
