version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp_app
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=cakephp_db
    depends_on:
      - db
    platform: linux/x86_64  # Force amd64 for web if compatibility issues persist

  db:
    image: mysql:5.7  # MySQL 5.7 image compatible with arm64
    container_name: cakephp_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cakephp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/x86_64  # Specific architecture for Mac M1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123456
    depends_on:
      - db
    platform: linux/x86_64

volumes:
  db_data:
